import turtle
pen = turtle.Turtle()
pen.color('purple')
pen.begin_fill()
pen.circle(100)
pen.end_fill()
pen.color('blue')
pen.begin_fill()
pen.circle(50)
pen.end_fill()
pen.color('red')
pen.begin_fill()
pen.circle(20)
pen.end_fill()