import turtle
tooga = turtle.Turtle()
tooga.turtlesize(2, 2, 2)
tooga.shape('turtle')
tooga.color('green')
tooga.penup()

pen = turtle.Turtle()
pen.pensize(10)
pen.color('yellow')
pen.penup()
pen.forward(100)
pen.left(90)
pen.pendown()
pen.forward(100)
pen.color('red')
pen.left(45)
pen.forward(150)
pen.left(90)
pen.forward(150)
pen.left(45)
pen.color('yellow')
pen.forward(200)
pen.left(90)
pen.forward(210)
pen.left(90)
pen.forward(100)

tooga.backward(250)
tooga.write("Tooga's House", font=('Open Sans', 30))
tooga.forward(250)
print("Tooga's house!")